import json
from datetime import datetime, timezone
from typing import Dict, Any, Optional

import yaml
from sqlalchemy.orm import Session

from app.db import models
from app.services.artifacts import artifact_service
from app.services.s3 import s3_client


class ReproBundleService:
    def build_manifest(self, run: models.Run) -> Dict[str, Any]:
        git_config = run.config.get("git") if isinstance(run.config, dict) else None
        return {
            "run_id": run.id,
            "project_id": run.project_id,
            "template_version_id": run.template_version_id,
            "created_at": run.created.isoformat() if hasattr(run, "created") else datetime.now(timezone.utc).isoformat(),
            "config": run.config,
            "git": {
                "repo": git_config.get("repo") if isinstance(git_config, dict) else None,
                "branch": run.git_branch,
                "commit": run.git_commit
            },
            "repro_artifacts": {
                "env_snapshot": "/manifest/env_snapshot.json",
                "requirements_freeze": "/manifest/requirements_freeze.txt",
                "git_diff": "/manifest/git_diff.patch",
                "git_status": "/manifest/git_status.txt",
                "run_fingerprint": "/manifest/run_fingerprint.json",
            },
        }

    def _generate_readme(self, run: models.Run, manifest: Dict[str, Any]) -> str:
        metrics = run.metrics or {}
        # Get final values
        final_win = metrics.get("winRate", [])[-1]["value"] if metrics.get("winRate") else "N/A"
        final_return = metrics.get("returnMean", [])[-1]["value"] if metrics.get("returnMean") else "N/A"
        
        git_info = "N/A"
        git_config = run.config.get("git")
        if git_config:
            repo = git_config.get("repo", "N/A")
            branch = run.git_branch or git_config.get("branch", "main")
            commit = run.git_commit or git_config.get("commit", "HEAD")
            git_info = f"Repo: {repo}\n- Branch: {branch}\n- Commit: {commit}"

        return f"""# Experiment: {run.name}

**Run ID**: `{run.id}`
**Date**: {manifest['created_at']}

## 📊 Results
- **Final Win Rate**: {final_win}
- **Final Return**: {final_return}

## 🧬 Configuration
See `config_resolved.json` (or `config_resolved.yaml`) for full hyperparameters.

### Environment
- **Env ID**: {run.env}
- **Algorithm**: {run.algo}

### Code Source
{git_info}

## 🚀 How to Reproduce

### 1. Setup Environment
Ensure you have Python 3.9+ and dependencies installed:
```bash
pip install -r requirements.txt
```

### 2. Run Reproduction Script
We have provided a script to automatically checkout the code and start training:
```bash
bash reproduce.sh
```

---
*Generated by RL Research Platform*
"""

    def _generate_reproduce_script(self, run: models.Run) -> str:
        git_config = run.config.get("git") if isinstance(run.config, dict) else None
        if not git_config or not git_config.get("repo"):
            return "#!/bin/bash\necho 'No git repository linked to this run. Cannot auto-reproduce.'"
            
        repo = git_config.get("repo")
        commit = run.git_commit or git_config.get("commit") or "main"
        algo_entrypoint = None
        algo_cfg = run.config.get("algo") if isinstance(run.config, dict) else None
        if isinstance(algo_cfg, dict):
            algo_entrypoint = algo_cfg.get("entrypoint")
        if not algo_entrypoint:
            return "#!/bin/bash\necho 'Missing algorithm entrypoint. Cannot auto-reproduce.'"
        
        # We assume the user runs this script in a clean dir
        return f"""#!/bin/bash
set -e

# 1. Clone Code
echo "Cloning {repo}..."
if [ -d "source_code" ]; then
    echo "Directory source_code exists, skipping clone."
else
    git clone {repo} source_code
fi

cd source_code

# 2. Checkout Commit
echo "Checking out {commit}..."
git checkout {commit}

# 3. Setup Virtualenv
python -m venv .venv
source .venv/bin/activate

# 4. Install Dependencies (Optional, adjust as needed)
FREEZE_FILE="../manifest/requirements_freeze.txt"
if [ -f "$FREEZE_FILE" ]; then
    echo "Installing frozen dependencies..."
    pip install -r "$FREEZE_FILE"
elif [ -f "requirements.txt" ]; then
    echo "Installing dependencies..."
    pip install -r requirements.txt
fi

# 5. Run Training
# We use the saved entrypoint and resolved config.
echo "Starting Training..."
export PYTHONPATH=$PYTHONPATH:.
python - <<'PY'
import inspect
import importlib
import json
import os
from pathlib import Path

ENTRYPOINT = "{algo_entrypoint}"
CONFIG_PATH = Path("../config_resolved.json")

def load_entrypoint(entrypoint: str):
    module_name, func_name = entrypoint.split(":", 1)
    module = importlib.import_module(module_name)
    return getattr(module, func_name)

def call_with_kwargs(func, context):
    signature = inspect.signature(func)
    params = signature.parameters
    if any(p.kind == inspect.Parameter.VAR_KEYWORD for p in params.values()):
        return func(**context)
    filtered = {key: value for key, value in context.items() if key in params}
    if filtered:
        return func(**filtered)
    if len(params) == 0:
        return func()
    if len(params) == 1:
        return func(context["config"])
    return func(context["config"], **filtered)

config = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
output_dir = Path("repro_output").resolve()
metrics_path = output_dir / "metrics.jsonl"
checkpoint_dir = output_dir / "checkpoints"
output_dir.mkdir(parents=True, exist_ok=True)
checkpoint_dir.mkdir(parents=True, exist_ok=True)

context = {
    "config": config,
    "run_id": "repro",
    "output_dir": str(output_dir),
    "metrics_path": str(metrics_path),
    "checkpoint_dir": str(checkpoint_dir),
}

func = load_entrypoint(ENTRYPOINT)
call_with_kwargs(func, context)
PY

# Note: You might need to adjust the python command depending on your project structure.
"""

    def generate(self, db: Session, run: models.Run) -> Dict[str, Any]:
        manifest = self.build_manifest(run)
        
        files = {
            "/manifest/repro_manifest.json": (json.dumps(manifest, indent=2), "application/json"),
            "/manifest/config_resolved.json": (json.dumps(run.config or {}, indent=2), "application/json"),
            "/manifest/config_resolved.yaml": (yaml.safe_dump(run.config or {}, sort_keys=False), "text/yaml"),
            "/manifest/README.md": (self._generate_readme(run, manifest), "text/markdown"),
            "/manifest/reproduce.sh": (self._generate_reproduce_script(run), "text/x-shellscript")
        }

        for path, (content, mime) in files.items():
            exists = (
                db.query(models.Artifact)
                .filter(models.Artifact.run_id == run.id, models.Artifact.path == path)
                .first()
                is not None
            )
            if not exists:
                artifact_service.write_artifact(db, run.id, path, content, mime)

        return manifest

    def get_manifest_url(self, run_id: str) -> str:
        key = artifact_service.build_object_key(run_id, "manifest/repro_manifest.json")
        return s3_client.presigned_get_url(key)


repro_bundle_service = ReproBundleService()
