import json
from datetime import datetime
from typing import Dict, Any, Optional

import yaml
from sqlalchemy.orm import Session

from app.db import models
from app.services.artifacts import artifact_service
from app.services.s3 import s3_client


class ReproBundleService:
    def build_manifest(self, run: models.Run) -> Dict[str, Any]:
        return {
            "run_id": run.id,
            "project_id": run.project_id,
            "template_version_id": run.template_version_id,
            "created_at": run.created.isoformat() if hasattr(run, "created") else datetime.utcnow().isoformat(),
            "config": run.config,
            "git": {
                "branch": run.git_branch,
                "commit": run.git_commit
            }
        }

    def _generate_readme(self, run: models.Run, manifest: Dict[str, Any]) -> str:
        metrics = run.metrics or {}
        # Get final values
        final_win = metrics.get("winRate", [])[-1]["value"] if metrics.get("winRate") else "N/A"
        final_return = metrics.get("returnMean", [])[-1]["value"] if metrics.get("returnMean") else "N/A"
        
        git_info = "N/A"
        git_config = run.config.get("git")
        if git_config:
            repo = git_config.get("repo", "N/A")
            branch = run.git_branch or git_config.get("branch", "main")
            commit = run.git_commit or git_config.get("commit", "HEAD")
            git_info = f"Repo: {repo}\n- Branch: {branch}\n- Commit: {commit}"

        return f"""# Experiment: {run.name}

**Run ID**: `{run.id}`
**Date**: {manifest['created_at']}

## 📊 Results
- **Final Win Rate**: {final_win}
- **Final Return**: {final_return}

## 🧬 Configuration
See `config_resolved.yaml` for full hyperparameters.

### Environment
- **Env ID**: {run.env}
- **Algorithm**: {run.algo}

### Code Source
{git_info}

## 🚀 How to Reproduce

### 1. Setup Environment
Ensure you have Python 3.9+ and dependencies installed:
```bash
pip install -r requirements.txt
```

### 2. Run Reproduction Script
We have provided a script to automatically checkout the code and start training:
```bash
bash reproduce.sh
```

---
*Generated by RL Research Platform*
"""

    def _generate_reproduce_script(self, run: models.Run) -> str:
        git_config = run.config.get("git")
        if not git_config or not git_config.get("repo"):
            return "#!/bin/bash\necho 'No git repository linked to this run. Cannot auto-reproduce.'"
            
        repo = git_config.get("repo")
        commit = run.git_commit or git_config.get("commit") or "main"
        
        # We assume the user runs this script in a clean dir
        return f"""#!/bin/bash
set -e

# 1. Clone Code
echo "Cloning {repo}..."
if [ -d "source_code" ]; then
    echo "Directory source_code exists, skipping clone."
else
    git clone {repo} source_code
fi

cd source_code

# 2. Checkout Commit
echo "Checking out {commit}..."
git checkout {commit}

# 3. Install Dependencies (Optional, adjust as needed)
if [ -f "requirements.txt" ]; then
    echo "Installing dependencies..."
    pip install -r requirements.txt
fi

# 4. Run Training
# Assuming standard python entrypoint. Adjust if using custom runner.
# We pass the config file from the bundle.
echo "Starting Training..."
export PYTHONPATH=$PYTHONPATH:.
python -m {run.algo} --config ../config_resolved.yaml

# Note: You might need to adjust the python command depending on your project structure.
"""

    def generate(self, db: Session, run: models.Run) -> Dict[str, Any]:
        manifest = self.build_manifest(run)
        
        files = {
            "/manifest/repro_manifest.json": (json.dumps(manifest, indent=2), "application/json"),
            "/manifest/config_resolved.yaml": (yaml.safe_dump(run.config or {}, sort_keys=False), "text/yaml"),
            "/manifest/README.md": (self._generate_readme(run, manifest), "text/markdown"),
            "/manifest/reproduce.sh": (self._generate_reproduce_script(run), "text/x-shellscript")
        }

        for path, (content, mime) in files.items():
            exists = (
                db.query(models.Artifact)
                .filter(models.Artifact.run_id == run.id, models.Artifact.path == path)
                .first()
                is not None
            )
            if not exists:
                artifact_service.write_artifact(db, run.id, path, content, mime)

        return manifest

    def get_manifest_url(self, run_id: str) -> str:
        key = artifact_service.build_object_key(run_id, "manifest/repro_manifest.json")
        return s3_client.presigned_get_url(key)


repro_bundle_service = ReproBundleService()
