log:
  level: info

db:
  user: determined
  password: determined
  host: determined-db
  port: 5432
  name: determined

checkpoint_storage:
  type: shared_fs
  host_path: /mnt/rl_runs/checkpoints
  storage_path: /mnt/rl_runs/checkpoints

resource_manager:
  type: agent

task_container_defaults:
  network_mode: bridge
